# Generated by Django 5.1.4 on 2025-01-29 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_status_account_estado'),
        ('transacciones', '0002_alter_transaccion_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('revertida', 'Revertida')], default='proceso', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='from_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('GBP', 'Libra esterlina'), ('JPY', 'Yen japonés'), ('MXN', 'Peso mexicano'), ('CAD', 'Dólar canadiense'), ('AUD', 'Dólar australiano'), ('CHF', 'Franco suizo'), ('CNY', 'Yuan chino'), ('SEK', 'Corona sueca')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='to_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='transa_ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
