# Generated by Django 5.1.4 on 2025-01-31 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_status_account_estado'),
        ('transacciones', '0003_remove_transaccion_cuenta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaccion',
            new_name='Transaction',
        ),
    ]
