# Generated by Django 5.1.4 on 2025-01-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_created_at_alter_account_saldo'),
        ('transacciones', '0003_transaction_delete_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cuenta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_destino', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cuenta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_origin', to='accounts.account'),
        ),
    ]
