# Generated by Django 5.1.4 on 2025-01-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_name_alter_account_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='status',
            new_name='estado',
        ),
    ]
