# Generated by Django 5.1.4 on 2025-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_status_account_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
